spring:  
  application:
    name: discovery-service
      
eureka:
  instance:
    hostname: ${HEROKU_APP_NAME}.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false